import profile from "../assets/images/profile.png";
import thumbnail from "../assets/images/thumbnail.png";
import cards from "../assets/images/cards.png";
import path from "../assets/images/path.png";
import logo from "../assets/images/logo.png";
import logoSmall from "../assets/images/logo-small.png";
import empty from "../assets/images/empty.png";
import google from "../assets/images/google.png";
import user from "../assets/images/user.png";
import uiux from "../assets/images/uiux.png";
import frontend from "../assets/images/frontend.png";
import backend from "../assets/images/backend.png";
import datascientist from "../assets/images/datascience.png";
import devops from "../assets/images/devops.png";
import productmanager from "../assets/images/productmanager.jpeg";
import fullstack from "../assets/images/fullstack.jpg";
import mobileapp from "../assets/images/mobileapp.jpeg";
import cloudarchitect from "../assets/images/cloudarchitect.jpg";

export default { profile, thumbnail, cards, path, logo, logoSmall, empty, google,user, uiux, frontend, backend, datascientist, devops, productmanager, fullstack, mobileapp, cloudarchitect};
